version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '02:00'
      timezone: Europe/Berlin
    groups:
      dependencies:
        dependency-type: production
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: development
        patterns:
          - '*'
    allow:
      - dependency-name: 'puppeteer'
      - dependency-name: 'puppeteer-core'
      - dependency-type: 'production'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'sunday'
      time: '03:00'
      timezone: Europe/Berlin
    groups:
      all:
        patterns:
          - '*'
