name: run-checks

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        # TODO: use macos-latest, windows-latest once active development is over.
        os: [ubuntu-latest]
        # Include all major maintenance + active LTS + current Node.js versions.
        # https://github.com/nodejs/Release#release-schedule
        # TODO: use more Node versions once active development is over.
        node: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run code checks
        run: |
          npm run lint

      - name: Run tests
        uses: nick-invision/retry@v2
        env:
          CHROMIUM: true
        with:
          max_attempts: 3
          command: npm run test
          timeout_minutes: 10
