name: Publish

permissions: read-all

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish @puppeteer/replay
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN_REPLAY}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish --access=public
